# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.ico', '.'), ('icon.png', '.')],
    hiddenimports=[
        'controller', 'settings', 'titlebar',
        'PIL.BmpImagePlugin', 'PIL.PngImagePlugin',
        'PIL.ImageTk', 'PIL.ImageDraw', 'PIL.ImageFont',
        'pystray', 'pystray._win32', 'pystray._base',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'unittest', 'pydoc', 'doctest', 'test',
        'pkg_resources', 'setuptools', 'distutils',
        'sqlite3', 'csv',
        'difflib',
        'tarfile', 'gzip', 'bz2', 'lzma',
        'ftplib', 'smtplib', 'imaplib', 'poplib',
        'xmlrpc', 'pydoc_data', 'lib2to3',
        'asyncio', 'concurrent', 'multiprocessing',
        'PIL.GifImagePlugin',
        'PIL.JpegImagePlugin', 'PIL.Jpeg2KImagePlugin',
        'PIL.TiffImagePlugin', 'PIL.WebPImagePlugin',
        'PIL.SgiImagePlugin',  'PIL.TgaImagePlugin',
        'PIL.PcxImagePlugin',  'PIL.PpmImagePlugin',
        'PIL.XbmImagePlugin',  'PIL.XpmImagePlugin',
        'PIL.ImImagePlugin',   'PIL.MspImagePlugin',
        'PIL.FliImagePlugin',  'PIL.DdsImagePlugin',
        'PIL.BlpImagePlugin',  'PIL.CurImagePlugin',
        'PIL.EpsImagePlugin',  'PIL.WmfImagePlugin',
        'PIL.PsdImagePlugin',  'PIL.SpiderImagePlugin',
        'PIL.SunImagePlugin',
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ImFine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
